name: Deploy Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 只上传1次，唯一 github-pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # 你的index.html所在目录，根目录就写 .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - id: deploy
        uses: actions/deploy-pages@v5
